// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/sea/Desktop/work/sea-ui/src/alert/index.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/sea/Desktop/work/sea-ui/src/alert/index.md?type=demo-index';

export const filesMeta = {
  'components/alert/index': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__alert" */'/Users/sea/Desktop/work/sea-ui/src/alert/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
