// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/sea/Desktop/work/sea-ui/node_modules/dumi/theme-default/slots/SearchBar/index.js';
export * from '/Users/sea/Desktop/work/sea-ui/node_modules/dumi/theme-default/slots/SearchBar/index.js';
